src/Entity/Animal.php
<?php

namespace App\Entity;

use App\Repository\AnimalRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnimalRepository::class)
 */
class Animal
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $name;

    /**
     * @var DateTime
     *
     * @ORM\Column(type="datetime")
     */
    private $birth_date;

    /**
     * @var float
     *
     * @ORM\Column(type="float")
     */
    private $height;

    /**
     * @var float
     *
     * @ORM\Column(type="float")
     */
    private $weight;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     */
    private $price;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $breed;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    private $adopted = false;

    /**
     * @var DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $adopted_at;

    /**
     * @ORM\ManyToOne(targetEntity=AnimalType::class, inversedBy="animals")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="animals")
     */
    private $owner;


    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return int
     */
    public function getPrice(): int
    {
        return $this->price;
    }

    /**
     * @param int $price
     * @return Animal
     */
    public function setPrice($price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string|null $name
     * @return $this
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getBirthDate(): ?DateTimeInterface
    {
        return $this->birth_date;
    }

    /**
     * @param DateTimeInterface $birth_date
     * @return $this
     */
    public function setBirthDate(DateTimeInterface $birth_date): self
    {
        $this->birth_date = $birth_date;

        return $this;
    }

    /**
     * @return float|null
     */
    public function getHeight(): ?float
    {
        return $this->height;
    }

    /**
     * @param float $height
     * @return $this
     */
    public function setHeight(float $height): self
    {
        $this->height = $height;

        return $this;
    }

    /**
     * @return float|null
     */
    public function getWeight(): ?float
    {
        return $this->weight;
    }

    /**
     * @param float $weight
     * @return $this
     */
    public function setWeight(float $weight): self
    {
        $this->weight = $weight;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getBreed(): ?string
    {
        return $this->breed;
    }

    /**
     * @param string|null $breed
     * @return $this
     */
    public function setBreed(?string $breed): self
    {
        $this->breed = $breed;

        return $this;
    }

    /**
     * @return bool|null
     */
    public function getAdopted(): ?bool
    {
        return $this->adopted;
    }

    /**
     * @param bool $adopted
     * @return $this
     */
    public function setAdopted(bool $adopted): self
    {
        $this->adopted = $adopted;

        return $this;
    }

    /**
     * @return DateTimeInterface|null
     */
    public function getAdoptedAt(): ?DateTimeInterface
    {
        return $this->adopted_at;
    }

    /**
     * @param DateTimeInterface|null $adopted_at
     * @return $this
     */
    public function setAdoptedAt(?DateTimeInterface $adopted_at): self
    {
        $this->adopted_at = $adopted_at;

        return $this;
    }

    /**
     * @return AnimalType|null
     */
    public function getType(): ?AnimalType
    {
        return $this->type;
    }

    /**
     * @param AnimalType|null $type
     * @return $this
     */
    public function setType(?AnimalType $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return User|null
     */
    public function getOwner(): ?User
    {
        return $this->owner;
    }

    /**
     * @param User|null $owner
     * @return $this
     */
    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }
}

src/Entity/AnimalType.php
<?php

namespace App\Entity;

use App\Repository\AnimalTypeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Entity(repositoryClass=AnimalTypeRepository::class)
 */
class AnimalType
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity=Animal::class, mappedBy="type")
     */
    private $animals;

    public function __construct()
    {
        $this->animals = new ArrayCollection();
    }


    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return $this
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Animal[]
     */
    public function getAnimals(): Collection
    {
        return $this->animals;
    }

    /**
     * @param Animal $animal
     * @return $this
     */
    public function addAnimal(Animal $animal): self
    {
        if (!$this->animals->contains($animal)) {
            $this->animals[] = $animal;
            $animal->setType($this);
        }

        return $this;
    }

    /**
     * @param Animal $animal
     * @return $this
     */
    public function removeAnimal(Animal $animal): self
    {
        if ($this->animals->removeElement($animal)) {
            // set the owning side to null (unless already changed)
            if ($animal->getType() === $this) {
                $animal->setType(null);
            }
        }

        return $this;
    }

    /**
     * @return string|null
     */
    public function __toString()
    {
        return $this->getName();
    }
}

src/Controller/AnimalController.php
<?php

namespace App\Controller;

use App\Entity\User;
use DateTime;
use Exception;
use Nzo\UrlEncryptorBundle\Encryptor\Encryptor;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\AccessDeniedException;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\AnimalRepository;
use App\Entity\Animal;
use Nzo\UrlEncryptorBundle\Annotations\ParamDecryptor;


/**
 * Class AnimalController
 * @package App\Controller
 * @Route("/animal")
 */
class AnimalController extends AbstractController
{
    /**
     * @var Encryptor
     */
    private $encryptor;


    /**
     * AnimalController constructor.
     * @param Encryptor $encryptor
     */
    public function __construct(Encryptor $encryptor)
    {
        $this->encryptor = $encryptor;
    }

    /**
     * @Route("/", name="animal")
     * @Template("animal/index.html.twig")
     * @return array
     * @throws Exception
     */
    public function index(): array
    {
        $em             = $this->getDoctrine()->getManager();
        /** @var AnimalRepository $repo */
        $repo           = $em->getRepository(Animal::class);
        $animals        = $repo->findBy(["adopted" => 0, "adopted_at" => null]);
        $animalsAdopted = $repo->findByAdoptedPreviousMonth();

        return compact('animals', 'animalsAdopted');
    }

    /**
     * @Route("/detail/{id}", name="animal_detail")
     * @Template("animal/detail.html.twig")
     * @ParamDecryptor(params={"id"})
     * @param int $id
     * @return array
     */
    public function detail(int $id): array
    {
        $em   = $this->getDoctrine()->getManager();
        /** @var AnimalRepository $repo */
        $repo = $em->getRepository(Animal::class);

        if (!$animal = $repo->find($id)) {
            throw new NotFoundHttpException("Animal not found !");
        }

        return compact('animal');
    }

    /**
     * @Route("/add_to_cart", name="animal_add_to_cart", methods={"POST"})
     * @param Request $request
     * @IsGranted("IS_AUTHENTICATED_FULLY")
     * @return JsonResponse
     * @throws Exception
     */
    public function addToCart(Request $request): JsonResponse
    {
        $em   = $this->getDoctrine()->getManager();
        /** @var AnimalRepository $repo */
        $repo = $em->getRepository(Animal::class);

        /** @var Animal $animal */
        if (!$animal = $repo->find($this->encryptor->decrypt(
            $request->request->get('id')
        ))) {
            throw new NotFoundHttpException("Cannot find animal !");
        }

        /** @var User $user */
        if (!$user = $this->getUser()) {
            throw new AccessDeniedException("Access Denied !");
        }

        if (!$animal->getAdopted()) {
            $animal->setAdopted(true);
            $animal->setAdoptedAt(new DateTime());

            $user->addAnimal($animal);

            $em->persist($user);
            $em->persist($animal);
        }

        $em->flush();

        return $this->json([
            'success'  => true,
            'cart'     => $user->getCart(),
        ]);
    }
}

templates/animal/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Animal Detail{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12">
            <div class="card">
                <div class="card-header">
                    {{ animal.name }}
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        <li class="list-group-item">
                            {{ animal.breed }} 
                        </li>
                        <li class="list-group-item">
                            Height : {{ animal.height}}<br>
                            Weight : {{ animal.weight}}<br>
                            Price : {{ animal.price}}<br>
                            Birthday : {{ animal.getBirthDate|date("m/d/Y", false) }}<br>
                            Age : {{"now"|date("Y")-animal.getBirthDate|date("Y", false)}}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        {% if animal.adopted == 0 and animal.adoptedAt is null %}
            <button class="btn btn-primary"
                    id="add-to-cart"
                    data-href="{{ path('animal_add_to_cart') }}"
                    data-id="{{animal.id|nzo_encrypt}}"
            >
                Add to cart
            </button>
        {% endif %}
    {% endif %}
{% endblock %}

templates/animal/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Animal{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <h3>Animals for adoption :</h3>
        </div>
    </div>
        <div class="row">
        {% for animal in animals %}
            <div class="col-md-3 col-lg-3 col-sm-6">
                <div class="card">
                    <div class="card-header">
                        {{ animal.name }}
                    </div>
                    <div class="card-body">
                        {{ animal.breed }}
                    </div>
                    <div class="card-footer">
                        <a href="{{ path('animal_detail', {'id' : animal.id|nzo_encrypt}) }}" class="btn btn-primary">
                            More info
                        </a>
                    </div>
                    
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12">
            <h3>Animals adopted last month :</h3>
        </div>
    </div>
    <div class="row">
        {% for animal in animalsAdopted %}
            <div class="col-md-3 col-lg-3 col-sm-6">
                <div class="card">
                    <div class="card-header">
                        {{ animal.name }}
                    </div>
                    <div class="card-body">
                        {{ animal.breed }} <br>
                        Adopted at : {{ animal.adoptedAt|date('d/m/Y') }}
                    </div>
                    <div class="card-footer">
                        <a href="{{ path('animal_detail', {'id' : animal.id|nzo_encrypt}) }}" class="btn btn-primary">
                            More info
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}