src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use DateTime;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @var DateTime
     *
     * @ORM\Column(type="datetime")
     */
    private $published_at;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @var Post
     *
     * @ORM\ManyToOne(targetEntity=Post::class, inversedBy="posts")
     */
    private $parent;

    /**
     * @var Post[]
     *
     * @ORM\OneToMany(targetEntity=Post::class, mappedBy="parent")
     */
    private $posts;


    /**
     * Post constructor.
     */
    public function __construct()
    {
        $this->posts = new ArrayCollection();
    }


    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string $title
     * @return $this
     */
    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string|null $description
     * @return $this
     */
    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return DateTime
     */
    public function getPublishedAt(): DateTime
    {
        return $this->published_at;
    }

    /**
     * @param DateTime $published_at
     * @return $this
     */
    public function setPublishedAt(DateTime $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    /**
     * @return User|null
     */
    public function getAuthor(): ?User
    {
        return $this->author;
    }

    /**
     * @param User|null $author
     * @return $this
     */
    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return $this|null
     */
    public function getParent(): ?self
    {
        return $this->parent;
    }

    /**
     * @param Post|null $parent
     * @return $this
     */
    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getPosts(): Collection
    {
        return $this->posts;
    }

    /**
     * @param Post $post
     * @return $this
     */
    public function addPost(self $post): self
    {
        if (!$this->posts->contains($post)) {
            $this->posts[] = $post;
            $post->setParent($this);
        }

        return $this;
    }

    /**
     * @param Post $post
     * @return $this
     */
    public function removePost(self $post): self
    {
        if ($this->posts->removeElement($post)) {
            // set the owning side to null (unless already changed)
            if ($post->getParent() === $this) {
                $post->setParent(null);
            }
        }

        return $this;
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Post;
use App\Repository\PostRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;


/**
 * Class BlogController
 * @package App\Controller
 * @Route("/blog")
 */
class BlogController extends AbstractController
{
    /**
     * @Route("/", name="blog")
     * @Template("blog/index.html.twig")
     * @return array
     */
    public function index(): array
    {
        $em    = $this->getDoctrine()->getManager();
        /** @var PostRepository $repo */
        $repo  = $em->getRepository(Post::class);
        $posts = $repo->findBy(['parent' => null]);

        return compact('posts');
    }
}

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Blog{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-12 col-lg-12 col-sm-12">
            <h3>Posts :</h3>
        </div>
    </div>

    <div class="row">
        {% for post in posts %}
            <ul class="list-group" style="margin-bottom: 15px">
                <li class="list-group-item">
                    <div class="card">
                        <div class="card-header">
                            {{ post.title }}
                        </div>
                        <div class="card-body">
                            {{ post.description }}
                        </div>
                        <div class="card-footer">
                            Published at : {{ post.publishedAt|date('d/m/Y') }} by {{ post.author }}
                        </div>
                    </div>
                </li>
                {% if post.posts is not empty %}
                    <li class="list-group-item" style="background-color: rgba(0,0,0,.03);">
                        <ul class="list-group" style="margin-bottom: 15px">
                            <li class="list-group-item">
                                <h5>Comments :</h5>
                            </li>
                            {% for comment in post.posts %}
                                <li class="list-group-item">
                                    <div class="card">
                                        <div class="card-header">
                                            {{ comment.author }}
                                        </div>
                                        <div class="card-body">
                                            {{ comment.description }}<br><br>

                                            Published at : {{ comment.publishedAt|date('d/m/Y') }}
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                {% endif %}
            </ul>
        {% endfor %}
    </div>
{% endblock %}